extends: [plugin:prettier/recommended]
env:
  node: true
  es2023: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: off
  no-param-reassign: off
  import/no-extraneous-dependencies: off
